name: test
on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.8'
    - name: Python version
      run: |
        python -V
